# Configuration Cloudflare (Mode Unified Assets) pour Salvia 🌿

name = "salvia"
compatibility_date = "2025-02-25"

[assets]
directory = "./dist"

[placement]
mode = "smart"

# Désactive workers.dev pour rester sur un site purement statique
# (Tu pourras configurer ton domaine personnalisé dans le dashboard)
workers_dev = false
